[tool.poetry]
name = "json_difference"
version = "0.1.0"
description = ""
authors = ["Dmitry Smirnov <smirnov@ura.ru>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
